config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # The option 'defaults: { format: :json }' will set `json` as the default response
  # format for all routes contained within the block of the namespace.
  # The namespace method in Rails routes makes it so it will automatically
   # look in a directory api, then in a subdirectory v1 for QuestionsController
  namespace :api, defaults: { format: :json } do
    # /api...
    namespace :v1 do
      # /api/v1...
      resources :questions
      # /api/v1/questions
      resource :session, only: [:create, :destroy]
    end
  end

  # This defines a `route` rule that says when
   # we receive a `GET` request with URL `/`
   # handle it using the WelcomeController, with
   # the index action inside that controller.
   # The `as` option is used for the helper url/
   # path, it overrides or generates helper
   # methods that you can use in your views or
   # controllers
  get('/', {to: 'welcome#index', as: :root})
  get '/contacts/new', {to: 'contacts#new'}
  post '/contacts', {to: 'contacts#create' }

 # question new page
  # when someone requests /questions/new it will be handled by the NEW method
  # inside of questions controller
  # get '/questions/new', {to: 'questions#new', as: :new_question}
  # get '/questions/:id', {to: 'questions#show', as: :question }

  # handles submission of new questions form
  # post 'questions', {to: 'questions#create', as: :questions}

  # question show page
  # adding the alias `as: :question` will create the helper paths/url to question_path
  # we can use these like so: question_path(<id>), question_url(<id>)
  # get '/questions/:id', {to: 'questions#show', as: :question}

  # question index page
  # get '/questions', {to: 'questions#index'}

  # question edit page
  # get '/questions/:id/edit', {to: 'questions#edit', as: :edit_question}

  # handles submission of form on the question edit page
  # patch '/questions/:id', {to: 'questions#update'}

  # delete '/questions/:id', {to: 'questions#destroy'}

  # this builds all of the above routes for us ;)

  #routes written inside of a block passed
  #to a 'resources' method will be pre-fixed by a path
  #corresponding to the passed in symbol
  #for example here we see that all nested routes will be
  #prefixed with '/questions/:question_id'
   resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :likes, shallow: true, only: [ :create, :destroy ]
    # The `shallow: true` named argument will separate routes
    # that require the parent from those that don't. Routes
    # that require the parent (i.e. index, new & create) will
    # not change
    # Roytes that don't require the parent (i.e. show, edit, update
    # destroy ) will have the parent prefix
    # (i.e. /question/:question_id/) removed

    # Use the 'on' named argument to specify how a
    # nested route behaves relative to its parent.

    # `on: :collection` means that it acts on the entire
    # resource. All questions in this case. new and create
    # act on the collection

    # `on: :member` means that it acts on a single resource.
    # A signle question in this case. edit, destroy, show and update
    # are all member routes
    get :liked, on: :collection
    resources :publishings, only: :create
   end

   resources :users, shallow: true, only: [:new, :create, :show] do
     resources :gifts, only: [:new, :create] do
       resources :payments, only: [:new, :create]
     end
   end

   resource :session, only: [:new, :create, :destroy]

   get "/auth/github", as: :sign_in_with_github
   get "/auth/:provider/callback", to: "callbacks#index"
   # get "/auth/github/callback", to: "callbacks#index"
   # get "/auth/facebook/callback", to: "callbacks#index"
   # get "/auth/twitter/callback", to: "callbacks#index"


   resources :job_posts

   #resources :sessions vs resource :session
   #resourc is singular and unlike 'resources' 'resource' will create routes that do CRUD operation on only one thing. There will be no index routes and no route will have a ':id' wild card.  When using a singular resource, the controller must still be PLURAL

   #routes for delayed job, when generating delayed job be sure to stop the Spring server in terminal by typing 'Spring stop'
   #to generate a delayed job from your terminal use rails g delayed_job:active_record
   match(
     "/delayed_job",
     to: DelayedJobWeb,
     anchor: false,
     via: [:get, :post]
   )
end

app/models/question.rb
class Question < ApplicationRecord
  has_many(:answers, dependent: :destroy)
  belongs_to :user
  # belongs_to :user adds a presence validation on the
  # association. i.e.
  # validates :user_id, presence: true
  has_many :likes, dependent: :destroy
  # The `has_many` below depends on the existence of
  # `has_many :likes` above.
  # If the one above doesn't exist, you will get an error. (Or
  # if the one above comes after).
  has_many :likers, through: :likes, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings#, source: :tag
  # If the name of the association (i.e. tags) is the same as the
  # source singularized (i.e. tag), then the `source:` named
  # argument can be omitted.
  #  We don't actually need to add an image field to the model with
  # Active Storage
  has_one_attached :image


  # This is the  Question model
  # We generated this file with the command:
  # rails g model question title:string body:text
  # This command also generates a migration file
  # in db/migrate

  # Rauls will add attr_accessors for all columns of
  # the database table. (i.e. id, title, body, created_at, updated_at)

  # Create validations by using the 'validates' method
  # The arguments are (in order):
  # - A column name as a symbol
  #  - Named arguments corresponding to the
  # validation rules you want to set.

  validates(:title, presence: true, uniqueness: true)
  # presence refuses any record with the column nil
  # or empty

  validates :body,
            presence: { message: "must exist"}, length: { minimum: 10 }

  validates :view_count,
            numericality:
              { greater_than_or_equal_to: 0 }

  # When a validation fails, ActiveRecord will not
  # save the model instance or any changes to the db.
  # You can view validation errors, by calling
  # the .errors method on the object itself.

  # To list them in a human friendly manner:
  # q.errors.full_messages

  # Custom validation
  # Be careful, the method for custom validations is
  # singular, otherwise it's almost exactly the same
  # as for regular validations.
  validate :no_monkey

  # before_validation is a lifecycle callback method
  # that allows us to respond to events during the
  # life of a model instance (i.e. being vaidated, being created, being updated etc.)

  before_validation :set_default_view_count

  # scopes
  # Create a scope with a class method
  # def self.most_recent(limit)
  #   order(created_at: :desc).limit(limit)
  # end
  # Scopes are such a commonly used feature, that
  # there's a way to create them quicker.
  # It takes a scope name and a lambda as a callback

  scope :most_recent, -> (limit) { order(created_at: :desc).limit(limit) }

  scope :search, -> (query) {
    where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%")
  }
  # equivalent to:
  # def self.search(query)
  #   where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%")
  # end

  scope :viewable, -> {
    where(aasm_state: [:published, :answered, :not_answered])
  }


  include AASM

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :featured
    state :answered
    state :not_answered
    state :archived

    event :publish do
      transitions from: :draft, to: :published
    end

    event :answer do
        transitions from: [:not_answered, :published], to: :answered
    end

    event :no_answer do
      transitions from: :published, to: :not_answered
    end

    event :archive do
      transitions to: :archived
    end
  end

  def tag_names
    self.tags.map(&:name).join(", ")
    # The & symbol is used to tell Ruby that the following argument
    # should be treated as a block given to the method. So the line:
    # self.tags.map(&:name).join(", ")
    # is equivalent to:
    # self.tags.map { |x| x.name }.join(", ")
    # So the above will iterate over the collection self.tags
    # and build an array with the result of the name method
    # called on every item. (We then join the array into a comma
    # separated string)
  end

  # Appending = at the end of a method name, allows us to implement
  # a `setter`. A setter is a method that is assignable.
  # Example:
  # q.tag_names = "stuff, yo"

  # The code in the example above would call the method we wrote
  # below where the value on the right hand side of the `=` would
  # become the argument to the method.

  # This is similar to implementing an `attr_writer`
  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      # Finds the first record with the given attributes, or
      # initializes a record (Tag.new) with the attributes
      # if one is not found.
      Tag.find_or_initialize_by(name: tag_name)
      # If a tag with name tag_name is not found,
      # it will call Tag.new(name: tag_name)
    end
  end

  private

  def no_monkey
    # &. is the safe navigation operator. It's used
    # like the `.` iperator to call methods on an
    # object. If the method doesn't exist for an
    # object `nil` will be returned instead of
    # getting an error
    if body&.downcase&.include?("monkey")
      # To make a record invalid, you must add a
      # validation error, using the errors `add`
      # method. Its arguments are (in order):
      # - A symbol for the invalid column
      # - An error message as a string.
      self.errors.add(:body, "must not have monkeys")
    end
  end

  def set_default_view_count
    # If you are writing to an attribute accessor,
    # you must prefix with self. which you do not
    # have to do if you are just reading it insead
    self.view_count ||= 0
    # self.view_count || self.view_count = 0
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    questions = Question.order(created_at: :desc)
    render json: questions, each_serializer: QuestionCollectionSerializer
  end

  def show
    question = Question.find(params[:id])
    render json: question, include: ['answers.author']
  end

  def create
    question = Question.new question_params
    question.user = current_user
    if question.save
      render json: { id: question.id }
    else
      render(
        json: { errors: question.errors },
        status: 422 # Unprocessable Entity
      )
    end
  end

  def destroy
    question = Question.find params[:id]
    question.destroy
    render json: { status: 200 }, status: 200
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit, :update, :destroy]


  def new
    @question = Question.new
  end

  def create
    # # The 'params' object available in controllers
    # # is composed of the query string, url params,
    # # and the body of a form
    # # (e.g. req.query + req.params + req.body)
    #
    # # A good trick to see if your routes are working
    # # and you're getting the data that you want, is to
    # # render the params as JSON. This is like doing
    # # res.send(req.body) in Express

    # Use 'require' on the params object to retrieve
    # the nested hash of a key usually corresponding to
    # the name-value pairs of a form

    # Then use permit to specify all input names that
    # are allowable (as symbols).
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      flash[:notice] = "Question created successfully"
      # if question is saved successfully redirect to question show page
      redirect_to question_path(@question)
    else
      # render views/questions/new.html.erb
      render :new
    end
  end

  def show
    # For the 'form_with' helper
    @answer = Answer.new
    # For the list of answers
    @answers = @question.answers.order(created_at: :desc)
    @like = @question.likes.find_by(user: current_user)
  end

  def index
    if params[:tag]
      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @questions = @tag.questions.viewable.order(created_at: :desc)
    else
      @questions = Question.viewable.order(created_at: :desc)
    end
    respond_to do |format|
      format.html { render }
      format.json { render json: @questions }
      # format.csv { render plain: "blah, blah" }
    end
  end

  def edit
    # unless can?(:crud, @question)
    #   redirect_to root_path, alert: 'Not Authorized'
    # end
  end

  def update
    # attempt to edit the existing question with new values
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "Question destoryed!"
    @question.destroy
    redirect_to questions_path
  end

  def liked
    @questions = current_user.liked_questions.order('likes.created_at DESC')
  end

  private

  def question_params
    # params.require(:question): We must have a question object on the params of this request
    # .permit(:title, :body): for security reasons we need to only permit the title and body keys/attributes of the question
    params.require(:question).permit(:title, :body, :tag_names, :image)
  end

  def find_question
    # get the current value inside of the db
    @question = Question.find params[:id]
  end

  def authorize!
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
  <%#= To create a form for a resource (i.e. a model), use
  the form_wth helper instead of form_tag. Its usual
  arguments are:
  - A named argument 'model' which is assigned an
  instance of a model (i.e. a new question)
  - A named argument 'local', which will prevent
  the form from submitting its data using AJAX.
  - A block that is passed the form object, where
   we build the HTML inside the form (i.e. labels,
   inputs, submission buttons, etc.)
    All data from the input fields a form built with this will have its name-value nested in a hash named
   after the class of the passed in model
   (e.g. <input type="text" name="question[title]" id="question_title"> => { "question": { "title": "What?"} })
   %>

<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%# https://guides.rubyonrails.org/form_helpers.html %>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <div>
    <%#= f.collection_check_boxes :tag_ids, Tag.order(name: :asc), :id, :name do |b| %>
      <!-- <div class="tag-wrapper"> -->
          <%#= b.check_box %>
          <%#= b.text.humanize %>
      <!-- </div> -->
    <% #end %>
      <%= f.label :tag_names %>
      <%= f.text_field :tag_names %>
    </div>
    <div>
      <%= f.file_field :image %>
    </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>


<script>
    $('#question_tag_names').selectize({
      delimiter: ',',
      persist: false,
      labelField: "name",
      valueField: "name",
      searchField: "name",
      options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
      create: function(input) {
          return {
            name: input
          }
      }
  });
</script>

app/views/questions/_list.html.erb
<% @questions.each do |question| %>
  <div>
    <h2><%= link_to question.title, question_path(question) %></h2>
    <p><%= question.body %></p>
    <hr>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Question Edit Page</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<% if @tag.present? %>
  <h2>Showing questions tagged by: <span class="badge badge-pill badge-primary"><%= @tag.name %></span></h2>
<% else %>
  <h2>All Questions</h2>
<% end %>

<%= render 'list' %>

app/views/questions/liked.html.erb
<h1>Liked Question</h1>

<%= render 'list' %>

app/views/questions/new.html.erb
<h1>Question New Page</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<%= image_tag @question.image.variant(resize: '500X500') if @question.image.attached? %>
<p><%= @question.body %></p>
<p><%= @question.created_at %></p>
<h4>Asked by: <%= link_to @question.user.full_name  || 'DELETED', @question.user %></h4>
<% unless @question.tags.empty? %>
<p>
  Tags:
  <% @question.tags.each do |tag|  %>
    <%= link_to(tag.name, questions_path(tag: tag.name), class: "badge badge-pill badge-primary")  %>
  <% end %>
  <%#= @question.tags.map(&:name).join(", ") %>
  <%#=
    Equivalent to:
    @question.tags.map { |t| t.name }.join(", ")
    %>
</p>
<% end %>

<% if can?(:crud, @question) %>
<div>
  <%= link_to "Edit", edit_question_path(@question)%>
  <%= link_to "Delete", question_path(@question), method: :delete, data: {confirm: "Are you sure?"} %>
</div>
<% end %>
<% if @question.draft? && can?(:publish, @question) %>
  <%= link_to "Publish", question_publishings_path(@question), method: :post, class: "btn btn-primary btn-sm" %>
<% end %>
<div>
  <% if @like.present? && can?(:destroy, @like) %>
    <%= link_to "Unlike", like_path(@like), method: :delete %>
  <% elsif can?(:like, @question)%>
    <%= link_to "Like", question_likes_path(@question), method: :post %>
  <% end %>
  <small>
    <%= pluralize(@question.likes.count, "like") %>
  </small>
</div>

<%= form_with(model: [@question, @answer], local: true) do |f| %>
<% if @answer.errors.any? %>
  <ul>
    <% @answer.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-group">
  <%= f.text_area(
  :body,
  cols: 50,
  rows: 5,
  placeholder: "What are your thoughts?",
  class: "form-control"
  ) %>
</div>
<%= f.submit "Answer" %>
<% end %>

<hr />

<ul class="answer-list">
  <% @answers.each do |answer| %>
    <li>
      <p>
        <%= answer.body %> <br />
        <% if can? :crud, answer %>
          <small>
            <%= link_to(
              "Delete",
              question_answer_path(@question, answer),
              method: :delete,
              data: {
                confirm: "Are you sure?"
              }
            ) %>
          </small>
        <% end %>
        |
        <small>
          Answered <%= time_ago_in_words(answer.created_at) %> ago
        </small>
      </p>
    </li>
  <% end %>
</ul>